// Generated by scripts/build_app.py - do not edit.
const VERSION = "2026-08-22T18:01-0770cd8d";
const CACHE = 'fringe-' + VERSION;
const ASSETS = [
  "./",
  "./index.html",
  "./data.json",
  "./manifest.json",
  "./icon-192.png",
  "./icon-512.png",
  "./edinburgh.pmtiles",
  "./vendor/fonts/Noto Sans Italic/0-255.pbf",
  "./vendor/fonts/Noto Sans Italic/256-511.pbf",
  "./vendor/fonts/Noto Sans Medium/0-255.pbf",
  "./vendor/fonts/Noto Sans Medium/256-511.pbf",
  "./vendor/fonts/Noto Sans Regular/0-255.pbf",
  "./vendor/fonts/Noto Sans Regular/256-511.pbf",
  "./vendor/maplibre-gl.css",
  "./vendor/maplibre-gl.js",
  "./vendor/pmtiles.js",
  "./vendor/sprites/dark.json",
  "./vendor/sprites/dark.png",
  "./vendor/sprites/dark@2x.json",
  "./vendor/sprites/dark@2x.png",
  "./vendor/sprites/light.json",
  "./vendor/sprites/light.png",
  "./vendor/sprites/light@2x.json",
  "./vendor/sprites/light@2x.png",
  "./vendor/style-dark.json",
  "./vendor/style-light.json"
];

// No skipWaiting() here on purpose: a new build waits until the page offers
// the Update banner and the reader accepts. Otherwise the app would reload
// itself out from under you mid-listing.
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache-first: the whole point is that Edinburgh has no signal in August.
self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  e.respondWith(caches.match(e.request, {ignoreSearch: true}).then(hit => {
    if (hit) return hit;
    return fetch(e.request).then(res => {
      if (res && res.ok && res.type === 'basic') {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(e.request, copy));
      }
      return res;
    }).catch(() => hit);
  }));
});

self.addEventListener('message', e => {
  if (e.data === 'skipWaiting') self.skipWaiting();
});
